name: Build Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
          default: true

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: build-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build workspace with no feature
        run: cargo build --workspace --release --target x86_64-unknown-linux-musl --no-default-features

      - name: Build workspace with default features
        run: cargo build --workspace --release --target x86_64-unknown-linux-musl

      - name: Build workspace with all features
        run: cargo build --workspace --release --target x86_64-unknown-linux-musl --all-features

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
          default: true

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: test-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Quick check
        run: cargo check --workspace --all-features

      - name: Test with no feature
        run: cargo test --workspace --no-default-features

      - name: Test with default features
        run: cargo test --workspace

      - name: Test with all features
        run: cargo test --workspace --all-features
